### ISSUE TITLE
Deadlocks with SSL hanging in opening socket

### ISSUE THREAD

**Issue by hendricius** [excon/excon#440]
Hi everybody!

Thanks for the awesome gem. We are having an issue with Sidekiq and Excon. We are running everything in a multi threaded environment. Perhaps you have a idea what could be the issue?

Symptoms:
- All sidekiq workers stop.
- When checking I see that most workers are hanging at exactly that location in the code (below)
- We had similar problems with Ruby default `http` that's why we switched to Excon.

Does anyone have a clue what I could change?

Thanks!

```
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/socket.rb:166:in `connect'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/ssl_socket.rb:140:in `connect'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/socket.rb:28:in `initialize'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/ssl_socket.rb:9:in `initialize'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/connection.rb:375:in `new'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/connection.rb:375:in `socket'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/connection.rb:105:in `request_call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/middlewares/mock.rb:47:in `request_call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/middlewares/base.rb:15:in `request_call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/middlewares/base.rb:15:in `request_call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/middlewares/base.rb:15:in `request_call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/excon-0.39.6/lib/excon/connection.rb:230:in `request'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/adapter/excon.rb:54:in `call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/request/url_encoded.rb:15:in `call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:933:in `fetch_access_token'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:956:in `fetch_access_token!'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:971:in `refresh!'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-ads-common-0.9.5/lib/ads_common/auth/oauth2_handler.rb:91:in `refresh_token!'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-ads-common-0.9.5/lib/ads_common/auth/oauth2_handler.rb:83:in `get_token'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-ads-common-0.9.5/lib/ads_common/auth/oauth2_handler.rb:75:in `auth_string'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-ads-common-0.9.5/lib/ads_common/savon_headers/oauth_header_handler.rb:45:in `generate_headers'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-ads-common-0.9.5/lib/ads_common/savon_headers/base_header_handler.rb:75:in `prepare_request'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-ads-common-0.9.5/lib/ads_common/savon_service.rb:103:in `block in execute_soap_request'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-1.2.0/lib/savon/client.rb:129:in `yield_objects'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-1.2.0/lib/savon/client.rb:122:in `process'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-1.2.0/lib/savon/client.rb:84:in `block in request'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-1.2.0/lib/savon/soap/request_builder.rb:56:in `call'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-1.2.0/lib/savon/soap/request_builder.rb:56:in `request'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-1.2.0/lib/savon/client.rb:86:in `request'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-ads-common-0.9.5/lib/ads_common/savon_service.rb:101:in `execute_soap_request'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-ads-common-0.9.5/lib/ads_common/savon_service.rb:80:in `execute_action'
/home/deployer/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/google-adwords-api-0.13.1/lib/adwords_api/v201406/campaign_service.rb:25:in `mutate'
```

**Comment by stakach** [comment]
I've been having issues with sidekiq too.
Using `fog` with `excon, '0.43.0'` works however all newer versions fail with

```
2015-02-05T07:28:12.699Z 4268 TID-x0k6c WARN: A non-blocking socket operation could not be completed immediately. - read would block (Errno::EWOULDBLOCK)
2015-02-05T07:28:12.699Z 4268 TID-x0k6c WARN: C:/Ruby193/lib/ruby/gems/1.9.1/gems/excon-0.44.1/lib/excon/socket.rb:45:in `read_nonblock'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/excon-0.44.1/lib/excon/socket.rb:45:in `readline'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/excon-0.44.1/lib/excon/response.rb:47:in `parse'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/excon-0.44.1/lib/excon/middlewares/response_parser.rb:6:in `response_call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/excon-0.44.1/lib/excon/connection.rb:372:in `response'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/excon-0.44.1/lib/excon/connection.rb:236:in `request'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-core-1.28.0/lib/fog/core/connection.rb:63:in `request'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-1.27.0/lib/fog/rackspace/core.rb:114:in `authenticate'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-1.27.0/lib/fog/rackspace/storage.rb:458:in `authenticate_v1'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-1.27.0/lib/fog/rackspace/service.rb:29:in `authenticate'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-1.27.0/lib/fog/rackspace/storage.rb:94:in `authenticate'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-1.27.0/lib/fog/rackspace/storage.rb:425:in `initialize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-core-1.28.0/lib/fog/core/service.rb:115:in `new'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-core-1.28.0/lib/fog/core/service.rb:115:in `new'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-core-1.28.0/lib/fog/storage.rb:21:in `new'
```

**Comment by geemus** [comment]
@starbelly I think this might be related to the changes we were working on recently. Could you take a peek? Looks like we are missing a rescue on one of the EWOULDBLOCKs somewhere probably. Thanks!

**Comment by geemus** [comment]
Actually, moving discussion to #471 as I think that more narrowly points at this issue (I think the original issue here may be distinct).

**Comment by matkam** [comment]
I'm seeing another similar issue. Happening with Carrierwave on model ```save```:

```
2015-04-15T22:28:08.019Z 27029 TID-ov7298vmg WARN: Thread TID-ov73d2mx0
2015-04-15T22:28:08.020Z 27029 TID-ov7298vmg WARN: /opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/ssl_socket.rb:122:in `select'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/ssl_socket.rb:122:in `rescue in initialize'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/ssl_socket.rb:119:in `initialize'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/connection.rb:387:in `new'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/connection.rb:387:in `socket'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/connection.rb:106:in `request_call'
/opt/cloudvm/gems/ruby/2.1.0/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/excon/middleware.rb:30:in `request_call'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/middlewares/mock.rb:47:in `request_call'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/cloudvm/gems/ruby/2.1.0/gems/excon-0.45.1/lib/excon/connection.rb:233:in `request'
/opt/cloudvm/gems/ruby/2.1.0/gems/fog-core-1.30.0/lib/fog/core/connection.rb:81:in `request'
/opt/cloudvm/gems/ruby/2.1.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request'
/opt/cloudvm/gems/ruby/2.1.0/gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:593:in `_request'
/opt/cloudvm/gems/ruby/2.1.0/gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:588:in `request'
/opt/cloudvm/gems/ruby/2.1.0/gems/fog-aws-0.1.2/lib/fog/aws/requests/storage/put_object.rb:43:in `put_object'
/opt/cloudvm/gems/ruby/2.1.0/gems/fog-aws-0.1.2/lib/fog/aws/models/storage/file.rb:212:in `save'
/opt/cloudvm/gems/ruby/2.1.0/gems/fog-core-1.30.0/lib/fog/core/collection.rb:51:in `create'
/opt/cloudvm/gems/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:261:in `store'
/opt/cloudvm/gems/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:80:in `store!'
/opt/cloudvm/gems/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:59:in `block in store!'
/opt/cloudvm/gems/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
/opt/cloudvm/gems/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:58:in `store!'
/opt/cloudvm/gems/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:375:in `store!'
/opt/cloudvm/gems/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:207:in `store_bundle!'
/opt/cloudvm/gems/ruby/2.1.0/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:429:in `block in make_lambda'
/opt/cloudvm/gems/ruby/2.1.0/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:224:in `call'
/opt/cloudvm/gems/ruby/2.1.0/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:224:in `block in halting_and_conditional'
/opt/cloudvm/gems/ruby/2.1.0/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:503:in `call'
/opt/cloudvm/gems/ruby/2.1.0/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:503:in `block in call'
/opt/cloudvm/gems/ruby/2.1.0/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:503:in `each'
/opt/cloudvm/gems/ruby/2.1.0/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:503:in `call'
/opt/cloudvm/gems/ruby/2.1.0/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:86:in `run_callbacks'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/callbacks.rb:302:in `create_or_update'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/persistence.rb:103:in `save'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/validations.rb:51:in `save'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/opt/cloudvm/gems/ruby/2.1.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:253:in `block in transaction'
/opt/cloudvm/gems/ruby/2.1.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:226:in `block (2 levels) in run_queries_on_shard'
/opt/cloudvm/gems/ruby/2.1.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:476:in `using_shard'
/opt/cloudvm/gems/ruby/2.1.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:225:in `block in run_queries_on_shard'
/opt/cloudvm/gems/ruby/2.1.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:462:in `keeping_connection_proxy'
/opt/cloudvm/gems/ruby/2.1.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:224:in `run_queries_on_shard'
/opt/cloudvm/gems/ruby/2.1.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:252:in `transaction'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/transactions.rb:208:in `transaction'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/transactions.rb:268:in `block in save'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
/opt/cloudvm/gems/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/transactions.rb:267:in `save'
```

**Comment by starbelly** [comment]
Created PR https://github.com/excon/excon/pull/503 which should fix the issue.

**Comment by geemus** [comment]
closed by #503

**Comment by geemus** [comment]
Released in 0.45.2

**Comment by starbelly** [comment]
@matkam can you confirm the new version solves your issue?

**Comment by matkam** [comment]
@starbelly Haven't had a chance to get back to this, and I've downgraded for now. I'll report back when I get a chance to test the new version. Thanks!

**Comment by michaelem** [comment]
I'm still seeing this issue (or something very similar) with multiple passenger instances and/or sidekiq workers. We use s3 to down and upload files to s3 and they eventually all stall. Downgrading to 0.38 fixes the issue :/

**Comment by starbelly** [comment]
My hunch (last patch) was wrong. That's what you get for going on hunches. Though, the code added was needed. Anyway, I will revisit this issue later on this evening or tomorrow.

**Comment by geemus** [comment]
@starbelly thanks, just let me know if there is anything I can do to help out.

**Comment by matkam** [comment]
Just FYI for anyone who is seeing stuck sidekiq workers, you can ```kill -TTIN <sidekiq-pid>``` to get a thread dump and see where its getting stuck. See: http://www.mikeperham.com/2013/05/03/dealing-with-stuck-workers/

**Comment by starbelly** [comment]
@matkam  and @michaelem  I'm not able to replicate (yet). Not using excon directly, but using fog, which I wouldn't think would matter. Anyway, maybe someone can help me with replication: 

```
connection = Fog::Storage.new(
    :region             => 'us-west-2',
    :provider           => 'AWS',
    ...
)

30.times do |i|
  `touch #{i}.txt`
end

threads = []
30.times do |i|
  txt_file = "#{i}.txt"
    threads << Thread.new {
    connection.directories[0].files.create(
      :key    => txt_file,
      :body   => File.open(txt_file),
      :public => false
    )
  }
end
threads.each(&:join)
```
 I also did the same downloading the files, no exceptions or errors. Are you uploading and downloading in the same thread? I tried that too, and had no problems ( except for signature times, but that's unrelated). Maybe it's the size of the files? Maybe I should try with bigger files? I don't want to get charged by amazon though : /

@geemus is there an easy way for generating headers to auth and upload to S3 via Fog without fog making the connection and so forth? I started ripping code out of fog-aws to do this, but it's spread out a bit.

**Comment by matkam** [comment]
@starbelly I think it is happening with bigger files. Doesn't have to be too big, maybe a few MB. The inbound (to AWS) transfer price is free so I wouldn't worry about that, though they do charge a few cents for monthly storage: https://aws.amazon.com/s3/pricing/

**Comment by starbelly** [comment]
@matkam Ahhhh, didn't know that. Upload all the things! Looks like download is free for the first GB too.

I tried with 3MB files, no errors or exceptions. I tried uploading, downloading, and both together. I've tried different ruby versions as well.  I'm going to try this on a different box later. 

```
files = []
30.times do |i|
  fname = "#{i}.txt"
  File.write(fname, 'A' * 3_048_576)
  files << fname
end

threads = []
files.each do |file|
  threads << Thread.new do
    connection.directories[0].files.create(
        key: file,
        body: File.open(file),
        public: false
    )
    connection.directories[0].files.each do |s3_file|
      out_file = 'IN_' + s3_file.key
      next if File.file?(out_file)
      local_file = File.open(out_file, 'w')
      local_file.write(s3_file.body)
      local_file.close
    end
  end
end

threads.each(&:join)
```

**Comment by stakach** [comment]
Is that test code being run inside a [sidekiq](https://github.com/mperham/sidekiq) worker?
I assume the error is only thrown when something would block a [celluloid](https://github.com/celluloid/celluloid) actor / cell.

Maybe, @tarcieri or @mperham if you have a moment, could eyeball the relevant code.

**Comment by michaelem** [comment]
@matkam I'll try to build an example.

**Comment by mperham** [comment]
never ever use `Timeout.timeout`. So far that's the only bad thing I've seen.

**Comment by geemus** [comment]
I don't think Timeout ends up getting used unless you are in ruby 1.8.7 or less, so I don't think it should be an issue here, but could be wrong.

**Comment by mperham** [comment]
@geemus Unfortunately you are mistaken, it's still broken by design in all Rubies.  I'm not saying it's the issue here but it can lead to very subtle bugs.

**Comment by geemus** [comment]
@mperham agreed. Sorry, to clarify, to the best of my knowledge if you are in Ruby > 1.8.7, excon will not call timeout (it instead relies on IO.select timeouts). The one remaining timeout usage is due to the inability to do it in this way in old rubies.

**Comment by mperham** [comment]
Ah, thanks for clarifying.  :+1:

**Comment by starbelly** [comment]
@stakach The test code was run by itself. I'll try to get a test using sidekiq together.  
@mperham as @geemus said it only exist for backwards compatibility. The reason for the move to IO.select timeouts was due to bugs with Timeout.timeout. Threads in Ruby break my heart : /

**Comment by starbelly** [comment]
I get erratic results trying this in sidekiq. On my macbook I get Errno::EPIPE  errors. On a Linux box I get 403 forbidden from AWS, complaining about a bad signature. Of course, stand alone works just fine. I've never used Sidekiq so I'm not familiar with the caveats of trying to run code like this within in it. @michaelem I'll wait on your example.

**Comment by michaelem** [comment]
This is more and more of a heisenbug to me. I can't reproduce it out of production and even in production it only appears seemingly with random requests.

Anyway, here is a backtrace from one of my stalled passenger instances:

```
App 32703 stderr: ------------------------------------------------------------
App 32703 stderr: # Thread: #<Thread:0x007fd6fc371358@/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:108 sleep>(Worker 1), alive = true
App 32703 stderr: ------------------------------------------------------------
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/ssl_socket.rb:122:in `select'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/ssl_socket.rb:122:in `rescue in initialize'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/ssl_socket.rb:119:in `initialize'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/connection.rb:387:in `new'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/connection.rb:387:in `socket'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/connection.rb:106:in `request_call'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/excon/middleware.rb:30:in `request_call'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/middlewares/mock.rb:47:in `request_call'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/middlewares/base.rb:15:in `request_call'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/middlewares/base.rb:15:in `request_call'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/middlewares/base.rb:15:in `request_call'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/excon-0.45.3/lib/excon/connection.rb:233:in `request'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/fog-core-1.30.0/lib/fog/core/connection.rb:81:in `request'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:593:in `_request'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:588:in `request'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/fog-aws-0.1.2/lib/fog/aws/requests/storage/get_object.rb:55:in `get_object'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/fog-aws-0.1.2/lib/fog/aws/models/storage/files.rb:61:in `get'
App 32703 stderr:     /home/radionov/apps/assets-server/releases/20150424081723/app/models/original.rb:31:in `block in download!'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/redis-objects-1.1.0/lib/redis/lock.rb:67:in `lock'
App 32703 stderr:     /home/radionov/apps/assets-server/shared/bundle/ruby/2.2.0/gems/redis-objects-1.1.0/lib/redis/objects/locks.rb:52:in `obtain_lock'
App 32703 stderr:     /home/radionov/apps/assets-server/releases/20150424081723/app/models/original.rb:30:in `download!'
App 32703 stderr:     /home/radionov/apps/assets-server/releases/20150424081723/app/models/original.rb:21:in `download'
App 32703 stderr:     /home/radionov/apps/assets-server/releases/20150424081723/app/models/resize.rb:42:in `resize!'
App 32703 stderr:     /home/radionov/apps/assets-server/releases/20150424081723/app/models/resize.rb:32:in `resize'
```

**Comment by starbelly** [comment]
This is a bastage! @michaelem Do you have some code you show or psudeo-code to represent what's going on in your sidekiq worker? From there, I can try to replicate.

**Comment by michaelem** [comment]
It's really just looking if a file is there, if so downloading it. Afterwards it checks if the md5 matches the one on s3 and stores the file on the local filesystem. The last working version of excon we've found is 0.42.1. One thing that might be relevant is that the s3 bucket has about 14 Million jpgs in it (we run a photo sharing site). Then again s3 should not behave differently when accessing single files directly.

```
if bucket.files.head(path)
  _data = bucket.files.get(path)

  # check if the downloaded file matches the one on s3
  if Digest::MD5.hexdigest( _data.body ) != _data.etag
    # report error & retry
  end

  store_locally( _data.body )
end
```

**Comment by starbelly** [comment]
Hey @michaelem Does version 0.43 not work for you?

**Comment by michaelem** [comment]
@starbelly we where on 0.42.1 now, I've just deployed with 0.43 to check. I'll get back to you as soon as I know (should be in an hour or so).

**Comment by ACPK** [comment]
@michaelem Was this fixed or would you recommend downgrading from 0.45.4 to 0.42.1?

**Comment by slbug** [comment]
Issue with deadlock in IO.select still happens sometimes. Free sidekiq threads stuck on IO.select while reading from redis, excon stuck on IO.select while reading AWS response

**Comment by slbug** [comment]
Here is isolated example with instructions. https://gist.github.com/slbug/7b4d791c80ebde4361b9 
Mine got stuck on 20th iteration. If you send TTIN signal to sidekiq, you will see that excon stuck on IO.select in lib/excon/ssl_socket.rb:122 same as some sidekiq thread inside redis gem.

**Comment by fourseven** [comment]
I had this today on production, have dumped the ruby backtrace and the gdb one to here - https://gist.github.com/fourseven/20acdeed4861242a7152 - it may be helpful to someone!

**Comment by slbug** [comment]
@fourseven so we found that it happens in both sidekiq 3.x with celluloid (your case) and 4.x without celluloid (my case)

**Comment by fourseven** [comment]
Interesting @slbug, did you manage to find a work-around (such as an excon downgrade)?

**Comment by slbug** [comment]
Nope. Currently i'm investigating number of descriptors and trying to debug this deadlock via gdb

**Comment by fourseven** [comment]
Ouch. Let me know if you want me to run anything – I restarted our workers since yesterday but can run things again next time it happens.

**Comment by fourseven** [comment]
Ouch. Let me know if you want me to run anything – I restarted our workers since yesterday but can run things again next time it happens.

**Comment by geemus** [comment]
Just let me know if there is anything I can do to help. Not a ton of experience with an issue like this, however, so I'm not sure I have much to offer (yet anyway).

**Comment by starbelly** [comment]
Hello, have been in hiatus, I'll take a look at all this later today.

**Comment by geemus** [comment]
@starbelly no worries.

I think we may have actually fixed this (there was a blocking read that should have been non-blocking in ssl socket connect). Not positive it would be the same issue, but it might be worth trying again with latest versions to see if things have improved.

**Comment by starbelly** [comment]
@geemus did not find any issues on my own. If anyone is still having problems, please let me know. Also, please let me know how to reproduce your issue.
